dst_entity_generate.settings:
  type: config_object
  label: 'DST Entity Generate Settings'
  mapping:
    sync_entities:
      type: sequence
      label: 'Select Entities'
    column_name:
      type: string
      label: 'Column Name'
    column_value:
      type: string
      label: 'Column Value'
